version: "3"

# Please copy clash.example.env to clash.env and fill in the variables

services:
    clash:
        image: ghcr.io/darknightlab/clash-docker:main
        # build: .
        container_name: clash
        restart: always
        command: ["-d", "/root/.config/clash", "-ext-ui", "/dashboard"] # ["-ext-ctl", "127.0.0.1:9090"]
        network_mode: host
        env_file:
            - clash.env
        volumes:
            - ./config:/root/.config/clash
    # clash-yacd:
    #     image: haishanh/yacd:latest
    #     container_name: clash-yacd
    #     restart: always
    #     ports:
    #         - 15700:80
