version: "3"

services:
    clash:
        image: ghcr.io/darknightlab/clash-docker:main
        # build: .
        container_name: clash
        restart: always
        command: ["-d", "/root/.config/clash", "-ext-ui", "/dashboard"] # ["-ext-ctl", "127.0.0.1:9090"]
        network_mode: host
        environment:
            - IPV6=true
            - MIXED_PORT=7890
            - SOCKS_PORT=7891
            - HTTP_PORT=7892
            - CONFIG_URL=
        volumes:
            - ./config:/root/.config/clash
    # clash-yacd:
    #     image: haishanh/yacd:latest
    #     container_name: clash-yacd
    #     restart: always
    #     ports:
    #         - 15700:80
