version: "3"

# Please copy clash.example.env to clash.env and fill in the variables
# if you set TRANSPARENT_PROXY to true, please enable ip_forward and ipv6_forward in your host
# sysctl -w net.ipv4.ip_forward=1
# sysctl -w net.ipv6.conf.all.forwarding=1

services:
  clash:
    image: ghcr.io/darknightlab/clash-docker:main
    # build: .
    container_name: clash
    restart: always
    command: ["-d", "/root/.config/clash", "-ext-ui", "/dashboard"] # ["-ext-ctl", "127.0.0.1:9090"]
    network_mode: host
    cap_add:
      - NET_ADMIN
    env_file:
      - clash.env
    volumes:
      - ./config:/root/.config/clash
